spring.application.name=artelab
server.port=8080
spring.main.banner-mode=off

spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.properties.hibernate.format_sql=true

security.jwt.expiration-minutes=60

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html
spring.profiles.active=dev

# Actuator: solo exponemos /actuator/health (sin detalle) para el HEALTHCHECK de Docker
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never