spring.datasource.url=jdbc:sqlite:artelab.db
spring.datasource.username=
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

logging.level.org.hibernate.SQL=DEBUG

usuarios.service.base-url=http://localhost:8081

security.jwt.secret=artelab-main-secret-change-me-in-development
security.auth.username=admin
security.auth.password=admin123