spring.application.name=artelab
server.port=8080
spring.main.banner-mode=off

spring.datasource.driver-class-name=org.sqlite.JDBC

spring.datasource.url=jdbc:sqlite:artelab.db
spring.datasource.username=
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=DEBUG

usuarios.service.base-url=http://localhost:8081

security.jwt.secret=artelab-main-secret-change-me-in-production
security.jwt.expiration-minutes=60
security.auth.username=admin
security.auth.password=admin123
